# yaml-language-server: $schema=https://json.schemastore.org/pubspec.json
name: catmovie
version: 2.5.0
publish_to: none
description: 支持扩展播放源的播放器
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2

  salomon_bottom_bar: ^3.3.2
  html: ^0.15.4
  webview_flutter: ^4.8.0
  modal_bottom_sheet: ^3.0.0

  # https://github.com/peng8350/flutter_pulltorefresh/issues/588
  pull_to_refresh_flutter3: ^2.0.2

  # cupertino_list_tile: ^0.2.0
  # flutter_html: ^2.1.5
  cached_network_image: ^3.3.1
  chewie: ^1.11.3
  video_player: ^2.8.7
  path_provider: ^2.1.3
  clipboard: ^0.1.3
  wakelock_plus: ^1.2.5
  desktop_webview_window: ^0.2.3
  url_launcher: ^6.3.0
  flutter_slidable: ^4.0.0
  auto_injector: ^2.0.4
  wakelock_web: ^0.4.0

  waterfall_flow: ^3.0.3

  file_picker: ^10.2.0
  share_plus: ^11.0.0

  equatable: ^2.0.5
  isar:
    hosted:
      name: isar
      url: https://pub.isar-community.dev/
    version: ^3.1.8

  isar_flutter_libs:
    hosted:
      name: isar_flutter_libs
      url: https://pub.isar-community.dev/
    version: ^3.1.8

  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1

  tuple: ^2.0.2
  flutter_easyloading: ^3.0.5
  executor: ^2.2.3

  flutter_cupertino_settings:
    path: packages/flutter_cupertino_settings
  flappy_search_bar:
    path: packages/flappy_search_bar_ns # https://github.com/d1y/flappy_search_bar_ns
  command_palette:
    path: packages/command_palette # https://github.com/d1y/command_palette
  simple:
    path: packages/simple
  xi:
    path: packages/xi

  webplayer_embedded:
    git: https://github.com/d1y/webplayer_embedded
  bitsdojo_window:
    git:
      url: https://github.com/bitsdojo/bitsdojo_window
      path: bitsdojo_window

  dio_cache_interceptor: ^3.5.0
  provider: ^6.1.2
  dio: ^5.4.3+1
  collection: ^1.18.0
  csslib: ^1.0.0
  protocol_handler: ^0.2.0
  event_bus: ^2.0.0
  window_manager: ^0.3.9

dev_dependencies:
  flutter_lints: ^6.0.0

  flutter_launcher_name:
    git:
      url: https://github.com/Dhanabhon/flutter_launcher_name

  # flutter_launcher_icons: ^0.14.4
  icons_launcher: ^3.0.1

  # flutter_native_splash: ^2.4.6

  isar_generator:
    hosted:
      name: isar_generator
      url: https://pub.isar-community.dev/
    version: ^3.1.8
  # isar_generator: ^3.1.0+1

  build_runner: ^2.4.4

  # flutter pub run change_app_package_name:main io.github.d1y.catmovie
  change_app_package_name: ^1.5.0

# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "小猫影视"

# flutter pub run flutter_native_splash:create
# flutter_native_splash:
#   image: 'design/logo_trans.png'
#   color: "#FF5733"
#   ios: true
#   android: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/nsfw.html
    - assets/data/source_help.txt
    - assets/images/movie_default.png
    - assets/images/image_faild.png
    - assets/data/play_tips.txt
    - assets/images/github_logo.png
    - assets/images/error.png

##HERE

# flutter pub run icons_launcher:create
icons_launcher:
  image_path: 'design/logo_round.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
      # iOS不支持透明
      image_path: 'design/logo_full.png'
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: false