#!/usr/bin/env zsh

echo "start build 小猫影视.ipa"
dart run script/add_builtin.dart > lib/builtin/maccms/maccms.dart
flutter build ios --release --no-codesign
cd build/ios/iphoneos
mkdir Payload
cd Payload
ln -s ../Runner.app
cd ..
zip -r 小猫影视.ipa Payload